---

constants:
  prefix: "p."
  key: "NzYzMDU0MTAzNTkxOTExNDc0.X3yHgw.wNfZZyzhTqqhHQdzwnWkNkkYCYI"
  owner_id: 493839592835907594
  url1: "https://pcsg-db-server.herokuapp.com/update"
  url2: "https://pcsg-db-server.herokuapp.com/download/"

guild_ids: 
  - 693608235835326464
  
channels:
  warn-logs: 925881561558171719
  member-logs: 925881592860250122
  message-logs: 925881610371477504
  monitor-logs: 925881625642942484
  join-logs: 925881515257257984
  welcome: 700214669003980801
  member-count: 925230935400665118
  vc-count: 925231096684249148
  name-channel: 834839533978779718
  flag-channel: 889605745283317840

roles:
  family: 755633133600112651
  visual: 898651374940749915
  aural: 898650851030216727
  verbal: 898651524773871658
  physical: 898651720987582575
  logical: 898651793356124170
  social: 898651835940876308
  solitary: 898651898549243985

level-roles:
  - 762190942316134400
  - 762192895477415966
  - 762192810924441610
  - 762870198481977375
  - 762193027979542581

non_cogs:
  - "main.py"
  - "database.py"
  - "config.py"
  
profanity:
  - " shit "
  - "bitch"
  - "dick"
  - "pussy"
  - "cunt"
  - " ass "

welcome_message: "Welcome {0} to the <:PCSGLETTERSWITHOUTBACKGROUND:828392100729978900> Family! <a:catholdheart:830938992081371157> You're the **{1}th Family Member <:holdheart:830939097518178375>**\nThank You for joining **The Study-Goals' E-School <a:movingstar:830939250513674311>**\n\nWe look forward to studying with you, Newbie E-Schooler! <a:party:830939382944628766>"

styles:
  visual: "Visual (Spacial) Learner.\nVisual learners are those who prefer learning by observing things. Using visual aids such as pictures, images, diagrams, and whiteboards help these learners understand information better. They easily visualize information, have a good sense of direction and usually like to draw and doodle. To learn more press here: https://www.time4learning.com/learning-styles/visual-spatial.html"
  aural: "Aural (Auditory) Learner.\nSound and music appeal to these learners who typically have a good sense of rhythm. These learners are usually singers or musicians who are familiar with different instruments and the sounds they make. Aural learners are good listeners who normally learn best through verbal presentations like lectures and speeches. Learn more here: https://www.time4learning.com/learning-styles/auditory-aural.html"
  verbal: "Verbal (Linguistic) Learner.\nThese learners prefer using words, both in speech and writing. They can easily express themselves and usually love to read and write. Verbal learners tend to have a vast vocabulary and excel in activities that involve speaking, debating, and journalism. To learn more, press here: https://www.time4learning.com/learning-styles/verbal-linguistic.html"
  physical: "Physical (Kinesthetic) Learner.\nWhether it’s by using their body or hands, these learners are all about the sense of touch. Physical activities and sports play a big part in these student’s lives. Getting hands-on is a must for these learners who love to tinker and learn best when they can do rather than see or hear. Learn more here.: https://www.time4learning.com/learning-styles/kinesthetic-tactile.html"
  logical: "Logical (Mathematical) Learner.\nIf there is logic, reasoning, and numbers involved, these learners are sure to excel. These students function and solve complex problems by employing strategies and a scientific way of thinking. Computer programming, math, and science are usually favored by these types of learners. Learn more here: https://www.time4learning.com/learning-styles/logical-mathematical.html"
  social: "Social (Interpersonal) Learner.\nLearning in groups and working with others is favored by social learners. These students know how to communicate effectively and enjoy collaborating with others, brainstorming, and discussing ideas and concepts. Social learners are generally good listeners who are thoughtful and understanding. You can find more information here: https://www.time4learning.com/learning-styles/social-interpersonal.html"
  solitary: "Solitary (Intrapersonal) Learner.\nThese students prefer to use self-study and work alone. They are independent, very self-aware, and in tune with their thoughts and feelings. These learners prefer being away from crowds and learn best in a quiet place where they can focus on the task at hand. Find out more here: https://www.time4learning.com/learning-styles/solitary-intrapersonal.html"
...