---

constants:
  prefix: "p."
  key: "something"
  owner_id: 493839592835907594

non_cogs:
  - "main.py"
  - "database.py"
  
profanity:
  - "shit"
  - "bitch"
  - "dick"
  - "pussy"
  - "cunt"
  - "ass"

...